blank_issues_enabled: true
contact_links:
 - name: Docs
   about: Choose this template to create a documentation issue.
   url: https://github.com/aishwarya24/HelloWorld/issues/new?assignees=&labels=area%2Fdocumentation&template=docs.md&title=%5BDocs%5D+Title&projects=aishwarya24%2FHelloWorld%2F1
 - name: Platform
   about: Choose this template to create a Yugabyte Platform issue.
 - name: Core
   about: Choose this template to create issues related to docDB, YSQL and YCQL.
 - name: UI
   about: Choose this template to create any UI issues with YugabyteDB.
  
   
