name: Docs
description: Choose this template to create a documentation issue.
title: "[Docs] Title"
labels: "area/documentation"
body:
  - type: textarea
      label : Provide a detailed description of the information you want to update/include in the YugabyteDB docs.
    validations:
      required: false       
   
        
