name: Docs
description: Choose this template to create a documentation issue.
title: "[Docs] Title"
labels: "area/documentation"
body:
- type: textarea
  id: documentation
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description <br> of the information <br> you want to update/include in the YugabyteDB docs.**
  validations:
    required: true 
    
   
        
