name: Docs
description: Choose this template to create a documentation issue.
title: "[Docs] Title"
labels: "area/documentation"
body:
  - type: textarea
  id: what-happened
  attributes:
    label: What happened?
    validations:
      required: false       
   
        
