name: Feature request
description: Choose this template to suggest an idea for this project.
title: "[New Feature] Title"
labels: "kind/new-feature"
body:
- type: textarea
  attributes:
    label: Description
    placeholder: |
   1. **Is your feature request related to a problem or an enhancement? Please describe.**
   2. **Provide a brief solution(if any) of what you want to happen.
  validations:
    required: true 
    
