name: Feature request
description: Choose this template to suggest an idea for this project.
title: "[New Feature] Title"
labels: "kind/new-feature"
body:
- type: textarea
  attributes:
    label: Description
    placeholder: |
    **Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true 
    
